name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create or Update ECR Repository
        run: |
          if aws ecr describe-repositories --region us-east-1 --repository-names deezy-nostr-client > /dev/null 2>&1; then
            echo "ECR repository already exists. Skipping creation."
          else
            aws ecr create-repository --repository-name deezy-nostr-client --region us-east-1
          fi

      - name: Build and push Docker image
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 729989983411.dkr.ecr.us-east-1.amazonaws.com
          docker build -t deezy-nostr-client .
          docker tag deezy-nostr-client:latest 729989983411.dkr.ecr.us-east-1.amazonaws.com/deezy-nostr-client:latest
          docker push 729989983411.dkr.ecr.us-east-1.amazonaws.com/deezy-nostr-client:latest

      - name: Deploy to AWS App Runner
        run: |
          aws apprunner create-service \
            --cli-input-json "{
              \"ServiceName\": \"your-service-name\",
              \"SourceConfiguration\": {
                \"AuthenticationConfiguration\": {},
                \"AutoDeploymentsEnabled\": false,
                \"CodeRepository\": {
                  \"RepositoryUrl\": \"729989983411.dkr.ecr.us-east-1.amazonaws.com/deezy-nostr-client\",
                  \"SourceCodeVersion\": {
                    \"Type\": \"BRANCH\",
                    \"Value\": \"latest\"
                  }
                }
              },
              \"InstanceConfiguration\": {
                \"Cpu\": \"512\",
                \"Memory\": \"1GB\",
                \"EnvironmentVariables\": [
                  {
                    \"Name\": \"PORT\",
                    \"Value\": \"3000\"
                  },
                  {
                    \"Name\": \"MICROSERVICE_KEY\",
                    \"Value\": \"ABC\"
                  },
                  {
                    \"Name\": \"REDIS_HOST\",
                    \"Value\": \"redis-19678.c238.us-central1-2.gce.cloud.redislabs.com\"
                  },
                  {
                    \"Name\": \"REDIS_PORT\",
                    \"Value\": \"19678\"
                  },
                  {
                    \"Name\": \"REDIS_TYPE\",
                    \"Value\": \"external\"
                  },
                  {
                    \"Name\": \"REDIS_PASSWORD\",
                    \"Value\": \"${{ secrets.REDIS_PASSWORD }}\"
                  }
                ]
              }
            }"
